# Generated by Django 3.2.19 on 2023-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_alter_product_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='A food preparation.', max_length=300, verbose_name='Short Description'),
        ),
    ]
