# Generated by Django 3.2.19 on 2023-06-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0030_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='A food preparation.', max_length=300, verbose_name='Short Description'),
        ),
    ]
