# Generated by Django 3.2.19 on 2023-07-17 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='start_hour',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
